# Generated by Django 4.1.2 on 2022-11-30 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'meal_class',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meal_units',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('HeightFt', models.SmallIntegerField()),
                ('HeightIn', models.SmallIntegerField()),
                ('Weight', models.SmallIntegerField()),
                ('Sex', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user')),
            ],
            options={
                'db_table': 'water_entry',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=50)),
                ('Sodium_mg', models.SmallIntegerField(max_length=20)),
                ('Potassium_mg', models.SmallIntegerField(max_length=20)),
                ('Phosphate_mg', models.SmallIntegerField(max_length=20)),
                ('Protein_g', models.SmallIntegerField(max_length=20)),
                ('Water_L', models.SmallIntegerField(max_length=20)),
                ('Serving_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.unit')),
            ],
            options={
                'db_table': 'food_item',
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('NumServings', models.DecimalField(decimal_places=2, max_digits=4)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.fooditem')),
                ('MealName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.mealclass')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user')),
            ],
            options={
                'db_table': 'food_entry',
            },
        ),
    ]
