# Generated by Django 4.1.3 on 2022-12-01 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=300)),
                ('Sodium_mg', models.SmallIntegerField(max_length=20, null=True)),
                ('Potassium_mg', models.SmallIntegerField(max_length=20, null=True)),
                ('Phosphate_mg', models.SmallIntegerField(max_length=20, null=True)),
                ('Protein_g', models.SmallIntegerField(max_length=20, null=True)),
                ('Water_L', models.SmallIntegerField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'food_item',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min_Sodium_mg', models.SmallIntegerField()),
                ('Max_Sodium_mg', models.SmallIntegerField()),
                ('Min_Potassium_mg', models.SmallIntegerField()),
                ('Max_Potassium_mg', models.SmallIntegerField()),
                ('Min_Phosphorous_mg', models.SmallIntegerField()),
                ('Max_Phosphorous_mg', models.SmallIntegerField()),
                ('Protein_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('M_Water_L', models.DecimalField(decimal_places=2, max_digits=5)),
                ('F_Water_L', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MealClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'meal_class',
            },
        ),
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_entry',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('HeightFt', models.SmallIntegerField()),
                ('HeightIn', models.SmallIntegerField()),
                ('Weight', models.SmallIntegerField()),
                ('Sex', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('NumServings', models.DecimalField(decimal_places=2, max_digits=4)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.fooditem')),
                ('MealName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.mealclass')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_entry',
            },
        ),
        migrations.CreateModel(
            name='Actuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Water_L', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sodium_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Potassium_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Phosphorous_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actuals',
            },
        ),
    ]
