# Generated by Django 4.1.2 on 2022-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Phosphate_mg',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Potassium_mg',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Protein_g',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Sodium_mg',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Water_L',
            field=models.SmallIntegerField(null=True),
        ),
    ]
