# Generated by Django 4.1.2 on 2022-11-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fdic',
            field=models.BigIntegerField(null=True),
        ),
    ]
