# Generated by Django 4.1.2 on 2022-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Phosphate_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Potassium_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Protein_g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Sodium_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Water_L',
            field=models.SmallIntegerField(),
        ),
    ]
