# Generated by Django 4.1.2 on 2022-11-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min_Sodium_mg', models.SmallIntegerField()),
                ('Max_Sodium_mg', models.SmallIntegerField()),
                ('Min_Potassium_mg', models.SmallIntegerField()),
                ('Max_Potassium_mg', models.SmallIntegerField()),
                ('Min_Phosphate_mg', models.SmallIntegerField()),
                ('Max_Phosphate_mg', models.SmallIntegerField()),
                ('Protein_g', models.SmallIntegerField()),
                ('M_Water_L', models.SmallIntegerField()),
                ('F_Water_L', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Phosphate_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Potassium_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Protein_g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Sodium_mg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Water_L',
            field=models.SmallIntegerField(),
        ),
    ]
