# Generated by Django 4.1.2 on 2022-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fooditem_fdic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Phosphate_mg',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Potassium_mg',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Protein_g',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Sodium_mg',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Water_L',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
    ]
