# Generated by Django 4.1.2 on 2022-11-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_fooditem_phosphate_mg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='Serving_size',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='UnitName',
        ),
    ]
