# Generated by Django 4.1.2 on 2022-11-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_fooditem_serving_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='FoodName',
            field=models.CharField(max_length=300),
        ),
    ]
